version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
     - npm install
  build:
    commands:
     - npm run build
  post_build:
    commands:
     - mv buildspec2.yml build/

artifacts:
  files:
   - '**/*'
  base-directory: 'build'
